apiVersion: v1
kind: apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  labels:
    name: teamcity-agent
spec:
  restartPolicy: Never
  serviceAccount: teamcity
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
  - name: teamcity-agent
    image: jetbrains/teamcity-agent
    resources:
      limits:
        memory: "1Gi"
        cpu: "2"
        ephemeral-storage: 500Mi
    env:
      - name: SERVER_URL
        value: 'https://teamcity.mydomain.local'
