apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocp-project-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ocp-project-deployer
subjects:
  - kind: ServiceAccount
    name: tc-bot
    namespace: dev